#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]
compatibility_date = "2024-12-01"
pages_build_output_dir = "./build/client"
send_metrics = false

# Node.js compatibility settings
[build]
command = "npm run build"
cwd = "."

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "production"
