name = "bolt-diy"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "./build/client"

# Environment variables
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]  
NODE_ENV = "production"
